### ISSUE TITLE
README pixel art

### ISSUE THREAD

**Issue by tristen** [mapbox/node-happytiff#1]
plz

**Comment by yhahn** [comment]
Silhouette animation in progress, will color + finish tonight.

![happytiff](https://cloud.githubusercontent.com/assets/83384/5765157/4ec48a06-9cc5-11e4-93d7-39186a4a47d4.gif)

**Comment by tristen** [comment]
:heart_eyes_cat:

**Comment by ian29** [comment]
this tiff is pretty happy
